server:
  port: ${SERVER_PORT:1130}
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://10.40.3.1:27017/notification}
  mail:
    host: smtp.gmail.com
    port: 587
    from_email: ${FROM_MAIL:noreply.unicloudpaybox@gmail.com}
    username: ${MAIL_USERNAME:noreply.unicloudpaybox@gmail.com}
    password: ${MAIL_PASSWORD:zrewcovlobtkumac}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  mvc:
    format:
      date-time: iso
      date: iso
      time: iso
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
springdoc:
  swagger-ui:
    path: /