package vn.unicloud.notification.enums;

public enum ResponseCode {
    // Common
    SUCCESS(0, "Success"),
    FAILED(1, "Failed"),
    COMMON_ERROR(2, "Common Error"),
    INVALID_PARAM(3, "Invalid param"),
    INVALID_SESSION(4, "Invalid session"),
    UNHANDLED_REQUEST(5, "Unhandled request"),
    REQUEST_WAS_EXPIRED(6, "Request was expired"),
    SECURITY_VIOLATION(7, "Security violation"),
    RESPONSE_BODY_NOT_FOUND(8, "Response body not found"),
    RESPONSE_ENCRYPTING_FAILED(9, "Response encrypting failed"),
    INVALID_ACCESS_TOKEN(10, "Invalid access token"),
    FILE_NOT_FOUND(11, "File not found"),
    INTERNAL_SERVER_ERROR(12, "internal server error"),
    INVALID_REFRESH_TOKEN(13, "Invalid refresh token"),
    EXISTED_OTP(14, "Existed OTP"),
    INVALID_OTP(15, "Invalid OTP"),

    // User
    EXISTED_EMAIL(100, "Existed email"),
    EXISTED_PHONE(101, "Existed phone"),
    OTP_WAS_EXPIRED(102, "OTP was expired"),
    ACCOUNT_DID_NOT_LINK(103, "Account did not link"),
    USER_NOT_FOUND(104, "User not found"),
    LOGIN_FAILED(105, "Login failed"),
    USER_CREATE_FAIL(106, "Create user failed"),
    CURRENT_PASSWORD_NOT_CORRECT(107, "Current password not correct"),
    EXISTED_PORTAL_NUMBER(108, "Existed portal number"),
    USER_NOT_LOGGED_IN(109, "User not logged in"),
    EXISTED_PHONE_OR_EMAIL(110, "Existed phone or email on keycloak"),

    // Nickname
    EXISTED_NICKNAME(201, "Existed Nickname"),

    // Merchant
    CREATE_MERCHANT_FAIL(301, "Create merchant failed"),
    MERCHANT_LOGIN_FAILED(302, "Merchant login failed"),
    INVALID_VIRTUAL_ACCOUNT(303, "Invalid virtual account"),
    THIRD_PARTY_API_ERROR(304, "Call third party error"),
    INVALID_MERCHANT(305, "Invalid merchant"),
    EXPIRED_VIRTUAL_ACCOUNT(306, "Expired virtual account"),
    EXISTED_BRAND_NAME(307, "Existed brand name"),
    INVALID_RECEIVE_ACCOUNT(308, "Invalid receive account"),
    MERCHANT_NOT_FOUND(309, "Merchant not found"),
    MERCHANT_NEXT_STATUS_INVALID(310, "Merchant next status is invalid"),
    DOCUMENT_NOT_FOUND(311, "Document not found"),
    EXISTED_DOCUMENT(312, "Existed document"),
    PROFILE_MERCHANT_NOT_FOUND(313, "Profile merchant not found"),

    ACCOUNT_NOT_FOUND(314, "Account not found"),
    EXISTED_PORTAL_ACCOUNT(315, "Existed portal account"),

    MERCHANT_NOT_APPROVE(316, " Merchant haven't approved"),
    MERCHANT_FEE_NOT_FOUND(317, " Merchant fee not found"),
    // VietQR
    TRANSACTION_TIMEOUT(401, "Scan QR code timeout"),
    INVALID_TRANSACTION_ID(402, "Invalid transactionId"),
    VIETQR_INVALID_VIRTUAL_ACCOUNT(403, "Invalid virtual account"),
    INVALID_AMOUNT(404, "Invalid amount"),
    INVALID_TRANSACTION_STATE(405, "Invalid transaction state"),
    TRANSACTION_CANCELED(406, "Canceled transaction"),
    TRANSACTION_FAILED(407, "Transaction failed"),
    TRANSACTION_EXPIRED(408, "Transaction expired"),

    // IBFT
    INVALID_SIGNATURE(501, "Invalid signature"),
    INVALID_CLIENT_ID(502, "Invalid clientId"),

    //Fee
    EXISTED_FEE_CODE(601, "Existed Fee Code"),

    FEE_NOT_FOUND(602, "Fee not found"),

    INVALID_FEE(603, "Invalid Fee"),

    INVALID_VALUE_TO_IN_BRACKET_FEE(604, "Value to have to greater than value from"),

    INVALID_EXPIRATION_DATE(605, "Invalid expiration date"),

    FEE_STATUS_NOT_MATCH(606, "Fee status cant be allowed"),


    INVALID_MAX_MONEY_FEE_METHOD_CD(607, "Invalid max money"),

    EXISTED_FEE(608, "Existed Fee by service type and merchant"),

    INVALID_INPUT_DATE(609, "Invalid date input"),

    EXISTED_FEE_MERCHANT(610, "Existed Fee by merchant"),


    INVALID_VALUE_TO_AND_VALUE_FROM_IN_BRACKET_FEE(604, "Value from have to equal value to plus one "),
    //Download file
    DOWNLOAD_FILE_FAIL(710, "Cant download file"),

    //Digital signatures
    INVALID_DIGITAL_SIGNATURE(810, "Digital signature doesn't match"),

    // Core bank
    CORE_BANK_TRANSACTION_DENIED(10001, "TRANSACTION_DENIED"),
    CORE_BANK_AGENCY_CODE_INVALID(10003, "AGENCY_CODE_INVALID"),
    CORE_BANK_TRANSACTION_NOT_PROCESS(10005, "TRANSACTION_NOT_PROCESS"),
    CORE_BANK_PAYMENT_ACCOUNT_ERROR(10006, "PAYMENT_ACCOUNT_ERROR"),
    CORE_BANK_TRANSACTION_ERROR(10008, "TRANSACTION_ERROR"),
    CORE_BANK_TRANSACTION_INVALID(10012, "TRANSACTION_INVALID"),
    CORE_BANK_AMOUNT_FORMAT_INVALID(10013, "AMOUNT_FORMAT_INVALID"),
    CORE_BANK_CARD_INVALID(10014, "CARD_INVALID"),
    CORE_BANK_PAYMENT_ACCOUNT_NOT_ACTIVE(10015, "PAYMENT_ACCOUNT_NOT_ACTIVE"),
    CORE_BANK_WRONG_DATA_FORMAT(10020, "WRONG_DATA_FORMAT"),
    CORE_BANK_INCOMPLETE_INFORMATION(10021, "INCOMPLETE_INFORMATION"),
    CORE_BANK_NO_DATA_FOUND(10022, "NO_DATA_FOUND"),
    CORE_BANK_ACCOUNT_INVALID(10023, "ACCOUNT_INVALID"),
    CORE_BANK_SERVER_ERROR(10024, "SERVER_ERROR"),
    CORE_BANK_ACCOUNT_BUSY(10025, "ACCOUNT_BUSY"),
    CORE_BANK_ACCOUNT_INACTIVE(10026, "ACCOUNT_INACTIVE"),
    CORE_BANK_BALANCE_NOT_ENOUGH(10027, "BALANCE_NOT_ENOUGH"),
    CORE_BANK_INVALID_ACCOUNT(10028, "INVALID_ACCOUNT"),
    CORE_BANK_INVALID_ACCOUNT_RECEIVER(10030, "INVALID_ACCOUNT_RECEIVER"),
    CORE_BANK_INVALID_PHONE_NUMBER(10031, "INVALID_PHONE_NUMBER"),
    CORE_BANK_INVALID_ID_CARD(10032, "INVALID_ID_CARD"),
    CORE_BANK_CREDIT_ACCOUNT_INVALID(10039, "CREDIT_ACCOUNT_INVALID"),
    CORE_BANK_APPLICATION_NOT_ACTIVE(10041, "APPLICATION_NOT_ACTIVE"),
    CORE_BANK_AMOUNT_LEAST_1000(10043, "AMOUNT_LEAST_1000"),
    CORE_BANK_AMOUNT_NOT_NUMBER(10044, "AMOUNT_NOT_NUMBER"),
    CORE_BANK_SOURCE_DESTINATION_ACCOUNT_SAME(10045, "SOURCE_DESTINATION_ACCOUNT_SAME"),
    CORE_BANK_PHONE_NUMBER_OR_ID_CARD_NOT_EXISTS(10046, "PHONE_NUMBER_OR_ID_CARD_NOT_EXISTS"),
    CORE_BANK_CASH_LIMITATION_IN_TRANSACTION(10048, "CASH_LIMITATION_IN_TRANSACTION"),
    CORE_BANK_CASH_LIMITATION_IN_DAY(10049, "CASH_LIMITATION_IN_DAY"),
    CORE_BANK_CASH_LIMITATION_INVALID(10050, "CASH_LIMITATION_INVALID"),
    CORE_BANK_TRANSACTION_REVERSAL_ERROR(10051, "TRANSACTION_REVERSAL_ERROR"),
    CORE_BANK_TRANSACTION_REVERED(10052, "TRANSACTION_REVERED"),
    CORE_BANK_REFUND_LEAST_3(10053, "REFUND_LEAST_3"),
    CORE_BANK_TRANSACTION_NOT_EXISTS(10054, "TRANSACTION_NOT_EXISTS"),
    CORE_BANK_AMOUNT_OVER(10061, "AMOUNT_OVER"),
    CORE_BANK_TRANSACTION_TIMEOUT(10068, "TRANSACTION_TIMEOUT"),
    CORE_BANK_ACCOUNT_OR_CARD_NO_INVALID(10076, "ACCOUNT_OR_CARD_NO_INVALID"),
    CORE_BANK_ACCOUNT_CURRENCY_INVALID(10760, "ACCOUNT_CURRENCY_INVALID"),
    CORE_BANK_SYSTEM_OVERLOAD(10090, "SYSTEM_OVERLOAD"),
    CORE_BANK_NOT_CONNECTION_BANK(10091, "NOT_CONNECTION_BANK"),
    CORE_BANK_NETWORK_LOST(10092, "NETWORK_LOST"),
    CORE_BANK_BANK_NOT_FOUND(10093, "BANK_NOT_FOUND"),
    CORE_BANK_TRANSACTION_DUPLICATE(10094, "TRANSACTION_DUPLICATE"),
    CORE_BANK_NAPAS_CONNECTION_ERROR(10096, "NAPAS_CONNECTION_ERROR"),
    CORE_BANK_TRANSACTION_EXISTS(10099, "TRANSACTION_EXISTS"),
    CORE_BANK_SERVER_MAINTAIN(10100, "SERVER_MAINTAIN"),
    CORE_BANK_TRANSACTION_CANNOT_PROCESS(10105, "TRANSACTION_CANNOT_PROCESS"),
    CORE_BANK_TRANSACTION_FAIL(10108, "TRANSACTION_FAIL"),
    CORE_BANK_INVALID_TRANSACTION(10112, "INVALID_TRANSACTION"),
    CORE_BANK_AMOUNT_FORMAT_ERROR(10113, "AMOUNT_FORMAT_ERROR"),
    CORE_BANK_INVALID_CARD(10114, "INVALID_CARD"),
    CORE_BANK_DESTINATION_ACCOUNT_NOT_FOUND(10121, "DESTINATION_ACCOUNT_NOT_FOUND"),
    CORE_BANK_NOT_TRANSFER_TO_SAVING_ACCOUNT(10123, "NOT_TRANSFER_TO_SAVING_ACCOUNT"),
    CORE_BANK_NOT_TRANSFER_TO_CREDIT_ACCOUNT(10124, "NOT_TRANSFER_TO_CREDIT_ACCOUNT"),
    CORE_BANK_CARD_EXPIRED(10154, "CARD_EXPIRED"),
    CORE_BANK_ACCOUNT_IS_INVALID(10176, "ACCOUNT_IS_INVALID"),
    CORE_BANK_DESTINATION_ACCOUNT_NOT_EXISTS(10192, "DESTINATION_ACCOUNT_NOT_EXISTS"),
    CORE_BANK_INVALID_BANKBIN(10193, "INVALID_BANKBIN"),
    CORE_BANK_TRANSACTION_NOT_EXECUTE(10196, "TRANSACTION_NOT_EXECUTE"),
    CORE_BANK_TRANSACTION_EXISTS_IN_SERVER(10199, "TRANSACTION_EXISTS_IN_SERVER"),
    CORE_BANK_INVALID_FROM_IBFLOCAL(10200, "INVALID_FROM_IBFLOCAL"),
    CORE_BANK_WRONG_PASSWORD(10201, "WRONG_PASSWORD"),
    CORE_BANK_PASSWORD_OR_PHONE_NUMBER_WRONG(10202, "PASSWORD_OR_PHONE_NUMBER_WRONG"),
    CORE_BANK_INVALID_USER(10203, "INVALID_USER"),
    CORE_BANK_ACTIVE_ERROR(10204, "ACTIVE_ERROR"),
    CORE_BANK_PHONE_NUMBER_DUPLICATE(10205, "PHONE_NUMBER_DUPLICATE"),
    CORE_BANK_LIST_ACCOUNT_ERROR(10206, "LIST_ACCOUNT_ERROR"),
    CORE_BANK_WRONG_NEW_PASSWORD(10207, "WRONG_NEW_PASSWORD"),
    CORE_BANK_WRONG_OLD_PASSWORD(10208, "WRONG_OLD_PASSWORD"),
    CORE_BANK_CHANGE_PASSWORD_ERROR(10209, "CHANGE_PASSWORD_ERROR"),
    CORE_BANK_LIST_ACCOUNT_NOT_FOUND(10210, "LIST_ACCOUNT_NOT_FOUND"),
    CORE_BANK_ACCOUNT_NOT_REGISTER(10211, "ACCOUNT_NOT_REGISTER"),
    CORE_BANK_WRONG_DATE_FORMAT(10212, "WRONG_DATE_FORMAT"),
    CORE_BANK_PHONE_NUMBER_SMS_INVALID(10214, "PHONE_NUMBER_SMS_INVALID"),
    CORE_BANK_METHOD_AUTHENTICATION_NOT_FOUND(10215, "METHOD_AUTHENTICATION_NOT_FOUND"),
    CORE_BANK_REQUEST_TIMEOUT(10216, "REQUEST_TIMEOUT"),
    CORE_BANK_WRONG_TRANSACTION_DATE(10217, "WRONG_TRANSACTION_DATE"),
    CORE_BANK_TRANSACTION_NOT_FOUND(10218, "TRANSACTION_NOT_FOUND"),
    CORE_BANK_FEE_INVALID(10219, "FEE_INVALID"),
    CORE_BANK_FEE_INCORRECT(10220, "FEE_INCORRECT"),
    CORE_BANK_VAT_INVALID(10221, "VAT_INVALID"),
    CORE_BANK_CANNOT_TAKE_CHALLENGE_CODE(10222, "CANNOT_TAKE_CHALLENGE_CODE"),
    CORE_BANK_CANNOT_CALCULATE_FEE(10223, "CANNOT_CALCULATE_FEE"),
    CORE_BANK_TIME_SEARCH_OVER_30_DAYS(10225, "TIME_SEARCH_OVER_30_DAYS"),
    CORE_BANK_TRANSACTION_DATE_EXPIRED(10226, "TRANSACTION_DATE_EXPIRED"),
    CORE_BANK_ID_CARD_INCORRECT(10227, "ID_CARD_INCORRECT"),
    CORE_BANK_PASSWORD_INCORRECT(10229, "PASSWORD_INCORRECT"),
    CORE_BANK_PHONE_NUMBER_NOT_REGISTER(10228, "PHONE_NUMBER_NOT_REGISTER"),
    CORE_BANK_NEW_PASSWORD_SAME_OLD_PASSWORD(10230, "NEW_PASSWORD_SAME_OLD_PASSWORD"),
    CORE_BANK_PACKAGE_SERVICE_NOT_SUPPORT(10231, "PACKAGE_SERVICE_NOT_SUPPORT"),
    CORE_BANK_ACTIVE_CODE_INCORRECT(10232, "ACTIVE_CODE_INCORRECT"),
    CORE_BANK_PASSWORD_EXPIRED(10233, "PASSWORD_EXPIRED"),
    CORE_BANK_OVER_TIME(10234, "OVER_TIME"),
    CORE_BANK_BILL_HAS_PAID(10235, "BILL_HAS_PAID"),
    CORE_BANK_OVER_TIME_IN_DAY(10236, "OVER_TIME_IN_DAY"),
    CORE_BANK_ORIGINAL_TRANSACTION_NOT_FOUND(10237, "ORIGINAL_TRANSACTION_NOT_FOUND"),
    CORE_BANK_CARD_NO_EXPIRED(10240, "CARD_NO_EXPIRED"),
    CORE_BANK_TRANSACTION_ANONYMOUS(10241, "TRANSACTION_ANONYMOUS"),
    CORE_BANK_WITHDRAW_OVER_TIME(10242, "WITHDRAW_OVER_TIME"),
    CORE_BANK_ACTIVE_LOGIN_BY_BIOMETRIC_ERROR(10243, "ACTIVE_LOGIN_BY_BIOMETRIC_ERROR"),
    CORE_BANK_CANCEL_LOGIN_BY_BIOMETRIC_ERROR(10244, "CANCEL_LOGIN_BY_BIOMETRIC_ERROR"),
    CORE_BANK_BIO_INCORRECT(10245, "BIO_INCORRECT"),
    CORE_BANK_NOT_ACTIVE_LOGIN_BY_BIOMETRIC(10246, "NOT_ACTIVE_LOGIN_BY_BIOMETRIC"),
    CORE_BANK_PHONE_NUMBER_OR_BIO_INCORRECT(10247, "PHONE_NUMBER_OR_BIO_INCORRECT"),
    CORE_BANK_CARD_LOST(10248, "CARD_LOST"),
    CORE_BANK_OWNER_NAME_CARD_NOT_FOUND(10250, "OWNER_NAME_CARD_NOT_FOUND"),
    CORE_BANK_OPEN_CLOSE_CARD_ERROR(10253, "OPEN_CLOSE_CARD_ERROR"),
    CORE_BANK_CARD_CLOSED(10254, "CARD_CLOSED"),
    CORE_BANK_CARD_OPENED(10255, "CARD_OPENED"),
    CORE_BANK_OPEN_CLOSE_ONLINE_CREDIT_CARD_ERROR(10256, "OPEN_CLOSE_ONLINE_CREDIT_CARD_ERROR"),
    CORE_BANK_PAYMENT_ECOM_CLOSED(10257, "PAYMENT_ECOM_CLOSED"),
    CORE_BANK_PAYMENT_ECOM_OPENED(10258, "PAYMENT_ECOM_OPENED"),
    CORE_BANK_INVALID_LOCK_TYPE(10259, "INVALID_LOCK_TYPE"),
    CORE_BANK_INVALID_UNLOCK_TYPE(10260, "INVALID_UNLOCK_TYPE"),
    CORE_BANK_CUSTOMER_CANCELED_SERVICE(10400, "CUSTOMER_CANCELED_SERVICE"),
    CORE_BANK_CUSTOMER_REGISTER_NEW(10410, "CUSTOMER_REGISTER_NEW"),
    CORE_BANK_CUSTOMER_REQUEST_EDIT_INFO(10411, "CUSTOMER_REQUEST_EDIT_INFO"),
    CORE_BANK_CUSTOMER_REQUEST_CLOSE_SERVICE(10412, "CUSTOMER_REQUEST_CLOSE_SERVICE"),
    CORE_BANK_CUSTOMER_REQUEST_FORGOT_PASSWORD(10413, "CUSTOMER_REQUEST_FORGOT_PASSWORD"),
    CORE_BANK_CLOSE_SERVICE(10414, "CLOSE_SERVICE"),
    CORE_BANK_CUSTOMER_REQUEST_CANCEL_SERVICE(10415, "CUSTOMER_REQUEST_CANCEL_SERVICE"),
    CORE_BANK_CUSTOMER_REQUEST_RESEND_PASSWORD(10416, "CUSTOMER_REQUEST_RESEND_PASSWORD"),
    CORE_BANK_CUSTOMER_WAITING_APPROVE_REGISTER(10420, "CUSTOMER_WAITING_APPROVE_REGISTER"),
    CORE_BANK_CUSTOMER_WAIT_APPROVE_UPDATE_INFO(10421, "CUSTOMER_WAIT_APPROVE_UPDATE_INFO"),
    CORE_BANK_CUSTOMER_WAIT_APPROVE_CLOSE_SERVICE(10422, "CUSTOMER_WAIT_APPROVE_CLOSE_SERVICE"),
    CORE_BANK_CUSTOMER_WAIT_APPROVE_PASSWORD(10423, "CUSTOMER_WAIT_APPROVE_PASSWORD"),
    CORE_BANK_CUSTOMER_WAIT_APPROVE_OPEN_SERVICE(10424, "CUSTOMER_WAIT_APPROVE_OPEN_SERVICE"),
    CORE_BANK_CUSTOMER_WAIT_APPROVE_CANCEL_SERVICE(10425, "CUSTOMER_WAIT_APPROVE_CANCEL_SERVICE"),
    CORE_BANK_CUSTOMER_WAIT_APPROVE_RESEND_PASSWORD(10426, "CUSTOMER_WAIT_APPROVE_RESEND_PASSWORD"),
    CORE_BANK_CUSTOMER_REGISTER_WAIT_APPROVE_ACTIVE(10480, "CUSTOMER_REGISTER_WAIT_APPROVE_ACTIVE"),
    CORE_BANK_CUSTOMER_PASSWORD_WAIT_APPROVE_ACTIVE(10481, "CUSTOMER_PASSWORD_WAIT_APPROVE_ACTIVE"),
    CORE_BANK_CUSTOMER_CLOSED(10490, "CUSTOMER_CLOSED"),
    CORE_BANK_CARD_NO_NOT_CORRECT(10495, "CARD_NO_NOT_CORRECT"),
    CORE_BANK_CUSTOMER_REJECT_REGISTER_SERVICE(10497, "CUSTOMER_REJECT_REGISTER_SERVICE"),
    CORE_BANK_CUSTOMER_SERVICE_CLOSED(10498, "CUSTOMER_SERVICE_CLOSED"),
    CORE_BANK_CUSTOMER_USING_SERVICE(10499, "CUSTOMER_USING_SERVICE"),
    CORE_BANK_CARD_NO_INVALID(10555, "CARD_NO_INVALID"),
    TEMPLATE_NOT_FOUND(105556, "TEMPLATE_NOT_FOUND"),
    TRIGGER_NOT_FOUND(105557, "TRIGGER_NOT_FOUND"),
    EXISTED_TRIGGER(105557, "VIOLATE_CONSTRAINT_TRIGGER"),
    INVALID_PATH_FORMAT(105558, "PATH_VALUE_FORMAT_{entity}/{event}"),


    //Digital signatures

    ;

    private final int code;
    private final String message;

    ResponseCode(int code, String message) {
        this.code = code;
        this.message = message;
    }

    public int getCode() {
        return code;
    }

    public String getMessage() {
        return message;
    }

    public static ResponseCode valueOf(long value) {
        for (ResponseCode responseCode : ResponseCode.values()) {
            if (responseCode.getCode() == value) {
                return responseCode;
            }
        }
        return null;
    }

    public static ResponseCode getCoreBankErrorCode(Integer coreBankCode) {
        if (coreBankCode == null) {
            return null;
        } else if (coreBankCode == 0) {
            return SUCCESS;
        } else {
            String code;
            if (coreBankCode > 99) {
                code = "10" + coreBankCode;
            } else if (coreBankCode > 9) {
                code = "100" + coreBankCode;
            } else {
                code = "1000" + coreBankCode;
            }

            ResponseCode responseCode = valueOf(Long.parseLong(code));
            return responseCode == null ? INTERNAL_SERVER_ERROR : responseCode;
        }
    }
}
